[package]
name = "blog-design"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tera = "1"
lazy_static = "1.4.0"
actix-files = "*"
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres" ] }
serde = { version = "1.0", features = ["derive"] }
